projekt/app/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('start', views.start, name="start"),
    path('home', views.home, name="home"),
    path('login/', views.login_user, name="login"), 
    path('logout/', views.logout_user, name="logout"),
    path('register/', views.create_user, name="register"),
    path('profil/', views.profil, name="profil"),
    path('edit/', views.edit, name="edit"),
    path('change_password/', views.change_password, name="change_password"),
    path('social-auth/', include('social_django.urls', namespace='social')),

      path('password_reset/',auth_views.PasswordResetView.as_view(template_name="account/password_reset.html"),name='password_reset'),
      path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_done.html"),name='password_reset_done'),
      path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_confirm.html"),name='password_reset_confirm'),
      path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name="account/password_reset_complete.html" ),name='password_reset_complete'),

      path('reg/', views.reg, name="reg"),
      path('pp/', views.pp, name="pp"),
      path('email/', views.contact, name="email"),
      path('contact/', views.contact, name="contact"),
]

projekt/predcar/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers
router = routers.DefaultRouter()
router.register('pred_car',views.Pred_carViews)
app_name='predcar'
urlpatterns = [
     
     path('api/', include(router.urls)),
   
    
     
     path('predcar/add/', views.create_view, name='add'),
     path('predictor_car', views.predictor_car, name='predictor_car'),
     
 
     path('pred/ajax/load-models/', views.load_models, name='ajax_load_models'),
    
]

projekt/predhouse/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers
router = routers.DefaultRouter()
router.register('pred_house',views.Pred_houseViews)
app_name='predhouse'
urlpatterns = [

     path('api/', include(router.urls)),
     
     path('predhouse/add/', views.create_view, name='add'),
     path('predictor_house', views.predictor_house, name='predictor_house'),
    
]

projekt/projekt/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('predhouse.urls')),
    path('', include('predcar.urls')),
    path('captcha/', include('captcha.urls'))
]

projekt/app/templates/base.html
<!DOCTYPE html>
<html>
<head>
{% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PredApp</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
    <div class="container">
       
        <div class="row px-3">
            
        <div class="col-lg-10 col-xl-9 card flex-row mx-auto px-0">
            <div class="img-left d-none d-md-flex "></div>
            
        <div class="card-body">
            <img src="/static/logo2.png" class="logo"/>
            <div class="container">
                
         
            </div>
            <div class="navb">
                {% if messages %}
                {% for message in messages %}
                <div class="text-center alert alert-warning alert-dismissible fade show" role="alert">
                  {{ message }}
                </div>
                {% endfor %}
                {% endif %}

                {% if user.is_authenticated %}
                <div  class="right"><small><strong> Witaj,  {{ user.username}}</strong></small></div>
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <a class="navbar-brand mx-auto" href="{% url 'home' %}">Stona główna</a>
                    
                    <a id="profil" class="navbar-brand mx-auto"  href="{% url 'profil' %}">Mój profil</a>
                    <a id="email" class="navbar-brand mx-auto" href="{% url 'email' %}">Kontakt</a>
                    <a class="navbar-brand mx-auto"  href="{% url 'logout' %}">Wyloguj</a>
                    {% endif %}
            
                    
                </nav>
            </div>
               
              {% block content %}
              {% endblock %}

              
        </div>
        </div> 
        </div>
    </div>
    
</body>


</html>

projekt/app/templates/change_password.html
{% extends 'base.html' %}
{% block content %}
           
<h2 class="text-center">Zmień hasło</h2>

<form method="POST" action="{% url 'change_password' %}">
    
    {% csrf_token %}
    <div class="form-group3">
    {% if form.errors %}
    <div class="alert alert-warning alert-dismissible fade show text-center" role="alert"> Nieprawidłowo wypełnione dane formularza 

        {% for field in form %}
            {% if field.errors %}
            {{ field.errors }}
            {% endif %}
        {% endfor %}
    </div>
    {% endif %}
        

    {{ form.as_p }}
</div>
    <input type="submit" value="Zmień hasło" class="btn btn-dark">
</form>
    {% endblock %}

projekt/app/templates/edit.html
{% extends 'base.html' %}
{% block content %}
       



<form method="POST" action="{% url 'edit' %}">
    

        <h2 class="text-left">Edytuj profil</h2>
    {% csrf_token %}
    <div class="form-group3">
    {% if form.errors %}
    <div class="alert alert-warning alert-dismissible fade show text-center" role="alert"> Nieprawidłowo wypełnione dane formularza 
        <div data-bs-theme="dark">
        </div>
        {% for field in form %}
            {% if field.errors %}
            {{ field.errors }}
            {% endif %}
        {% endfor %}
    </div>
    {% endif %}
    

    {{ form.as_p }}
    </div>
    <input type="submit" value="Edytuj" class="btn btn-dark">
    <p><small><a id="ch-pass" href="{% url 'change_password' %}"> Kliknij tutaj</a> żeby zmienić hasło</small></p>
</div>
</form>
    {% endblock %}

projekt/app/templates/home.html
{% extends 'base.html' %}
{% block content %}
           
{% if user.is_authenticated %}

<hr class="my-4">
<form method="POST" action class="form-box px-3">
              

<div class="text-center">
  <h4>Witaj w PredApp</h4>
  <hr class="my-4">
  <p>Dzięki użyciu aplikacji możesz poznać <br>orientacyjną cenę wybranego modelu samochodu<br> lub dowiedzieć się, ile będziesz musiał<br>zapłacić za wynajem mieszkania w Warszawie.<br> Przejdź do symulacji! 
    </p>
<div class="mb-2">
  <button type="submit"  class="btn  btn-block text-uppercase">
      <a  class="btn btn-dark" id="car"  href="{% url 'predcar:add' %}">Ceny samochodów</a>
  </button>
  <div class="mb-2">
    <button type="submit" class="btn  btn-block text-uppercase">
        <a  class="btn btn-dark" id="house" href="{% url 'predhouse:add' %}">Ceny mieszkań</a>
    </button>




</div>

<hr class="my-4">
</form>





{% endif %}


    {% endblock %}

projekt/app/templates/login.html
{% extends 'base.html' %}
{% block title %}
Login
{% endblock %}


{% block content %}



            

            <form method="POST" action class="form-box px-3">
              
                {% csrf_token %}
              <div class="form-group">
                
                <label for="login">Login</label>
                <span><i class="fa fa-envelope-o"></i></span>
                <input type="text" class="form-control" id="login" aria-describedby="loginHelp" name="username">
              </div>
              <div class="form-group">
                <label for="password">Hasło</label>
                <span><i class="fa fa-key"></i></span>
                <input type="password" class="form-control" id="password"name="password">
              </div>
              <div class="mb-2 butt">
              <button type="submit" class="btn  btn-block text-uppercase">Zaloguj się</button>
                </div>

                <div class="tex">
                  <a href="{% url 'password_reset' %}" class="forget-link">Przypomnij hasło</a>
                </div>


              
                <div class="p col-6">
                    <button class="loginBtn loginBtn--google ">
                      <a class="social" href="{% url 'social:begin' 'google-oauth2' %}"> Zaloguj przez   Google    </a>
                    </button>
                </div>
                
                  <div class="p col-6">
                      <button class="loginBtn loginBtn--facebook">
                        <a class=" social" href="{% url 'social:begin' 'facebook' %}">Zaloguj przez Facebook</a>
                      </button>
                  </div>
              
                  <hr class="my-4">
                  <div class="text-center mb-2">Nie posiadasz jeszcze konta?<p></p>
                    <a href="{% url 'register' %}">Zarejestruj się</a>
                  </div>
                 
    
            </form>


            

{% endblock %}

projekt/app/templates/password_reset_complete.html
{% extends "base.html" %}

{% block title %}
Password reset
{% endblock %}
{% block content %}
<h1>Password set</h1>

<p>Your password has been set. You can <a href="{% url 'login' %}">log in now</a></p>

{% endblock %}

projekt/app/templates/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}

Reset your password

{% endblock %}
{% block content %}
<h1>Reset your password</h1>
{% if validlink %}<p>
    Please enter your new password twice:</p>
    <form action="." method="post">{{ form.as_p }}{% csrf_token %}<p>
    <input type="submit" value="Change my password" /></p></form>
    {% else %}
    <p>The password reset link was invalid, possibly because it hasalready been used. Please request a new password reset.</p>
    {% endif %}
    
    {% endblock %}

projekt/app/templates/password_reset_done.html
{% extends "base.html" %}
{% block title %}
Reset your password{
    
    % endblock %}{% block content %}
<h1>Reset yourpassword</h1>
<p>We've emailed you instructions for setting your password.</p>
<p>If you don't receive an email, please make sure you've entered theaddress you registered with.</p>

{% endblock %}

projekt/app/templates/password_reset_email.html
{{ protocol }}://{{ domain }}{% url "password_reset_confirm" uidb64=uid token=token %}Your username, in case you've forgotten: {{ user.get_username }}

projekt/app/templates/password_reset_form.html
{% extends "base.html" %}

{% block title %}
Reset your password

{% endblock %}
{% block content %}
<h1>Forgotten your password?</h1>
<p>Enter your e-mail address to obtain a new password.</p>
<form action="." method="post">{{ form.as_p }}<p><input type="submit" value="Send e-mail"></p>{% csrf_token %}</form>
{% endblock %}

projekt/app/templates/pp.html
{% extends 'baseapp.html' %}

{% block content %}
<h4 class="titlee text-center">Regulamin Aplikacji</h4>
<hr class="my-4">
            

            <form method="POST" action class="form-box px-3">
                {% csrf_token %}
                <div class="text-left mb-2">
                 <small>  1. Wstęp<br>
                   <p>Niniejsza Polityka Prywatności określa zasady przetwarzania danych osobowych użytkowników aplikacji PredApp oraz ich prawa związane z ochroną prywatności.</p>
                  2. Definicje <br>
                   - Aplikacja: oznacza aplikację PredApp oraz wszystkie jej funkcjonalności i usługi dostępne za pośrednictwem aplikacji.<br>
                   - Użytkownik: oznacza osobę fizyczną lub prawną korzystającą z aplikacji.<br>
 - Właściciel aplikacji: oznacza osobę fizyczną lub prawną posiadającą prawa do aplikacji<br>
 - Dane osobowe: oznaczają wszelkie informacje dotyczące zidentyfikowanej lub możliwej do zidentyfikowania osoby fizycznej.</p>
3. Przetwarzanie danych osobowych<br>
 - Właściciel aplikacji przetwarza dane osobowe użytkowników wyłącznie w celu świadczenia usług za pośrednictwem aplikacji oraz w celach analitycznych i statystycznych.<br>
 - Użytkownik ma prawo dostępu do swoich danych osobowych oraz ich poprawiania lub usuwania.<br>
 - Właściciel aplikacji zobowiązuje się do ochrony danych osobowych użytkowników zgodnie z obowiązującymi przepisami o ochronie danych osobowych.<br>
 - Właściciel aplikacji może udostępniać dane osobowe użytkowników podmiotom trzecim wyłącznie w celu świadczenia usług za pośrednictwem aplikacji oraz w celach analitycznych i statystycznych.<br>
 - Właściciel aplikacji zastrzega sobie prawo do zmiany Polityki Prywatności w dowolnym czasie, z zachowaniem obowiązujących przepisów o ochronie danych osobowych.<br>
</small>     
                </div>


              
                  <hr class="my-4">
                  <div class="text-center mb-2">Nie posiadasz jeszcze konta?
                    <a href="{% url 'register' %}">Zarejestruj tutaj</a>
                  </div>
                  <div class="text-center mb-2">Posiadasz konto?
                    <a href="{% url 'login' %}">Przejdż do logowania</a>
                  </div>
    
            </form>




{% endblock %}

projekt/app/templates/reg.html
{% extends 'baseapp.html' %}

{% block content %}
<h4 class="titlee text-center">Regulamin Aplikacji</h4>
<hr class="my-4">
            

            <form method="POST" action class="form-box px-3">
                {% csrf_token %}
                <div class="text-left mb-2">
                 <small>  1. Wstęp<br>
                   <p>Niniejszy Regulamin określa zasady korzystania z aplikacji PredApp oraz obowiązki użytkowników i właściciela aplikacji. Regulamin jest integralną częścią umowy pomiędzy użytkownikiem a właścicielem aplikacji.</p> 

                  2. Definicje <br>

 - Aplikacja: oznacza aplikację PredApp oraz wszystkie jej funkcjonalności i usługi dostępne za pośrednictwem aplikacji.<br>
 - Użytkownik: oznacza osobę fizyczną lub prawną korzystającą z aplikacji.<br>
 <p>- Właściciel aplikacji: oznacza osobę fizyczną lub prawną posiadającą prawa do aplikacji.</p>
3. Zasady korzystania z aplikacji<br>
 - Użytkownik ma prawo korzystać z aplikacji zgodnie z jej przeznaczeniem i zasadami określonymi w regulaminie.<br>
 - Użytkownik zobowiązuje się do niepodejmowania działań mających na celu naruszenie praw właściciela aplikacji lub osób trzecich.<br>
 - Użytkownik zobowiązuje się do niepodejmowania działań mających na celu wyłudzenie lub uzyskanie nieuprawnionego dostępu do danych osobowych lub innych danych użytkowników aplikacji.<br>
 <p>- Właściciel aplikacji zastrzega sobie prawo do usunięcia lub zablokowania dostępu użytkownika do aplikacji w przypadku naruszenia zasad określonych w regulaminie lub obowiązującym prawie.</p>
 4. Odpowiedzialność<br>     
 - Użytkownik ponosi pełną odpowiedzialność za treści, które publikują w aplikacji lub przekazują osobom trzecim za pośrednictwem aplikacji.<br>
 - Właściciel aplikacji nie ponosi odpowiedzialności za treści publikowane przez użytkowników, chyba że właściciel aplikacji miał wiedzę o ich nielegalności i nie podjął działań mających na celu usunięcie takich treści.<br>
 - Właściciel aplikacji nie ponosi odpowiedzialności za szkody powstałe w wyniku korzystania lub niemożności korzystania z aplikacji.<br>
 - Właściciel aplikacji zastrzega sobie prawo do wprowadzania zmian w aplikacji oraz jej funkcjonalności bez uprzedniego powiadomienia użytkowników.<br>
 - Właściciel aplikacji zastrzega sobie prawo do usunięcia lub zablokowania dostępu użytkownika do aplikacji w przypadku naruszenia zasad określonych w regulaminie lub obowiązującym prawie.
</small>     
                </div>


              
                  <hr class="my-4">
                  <div class="text-center mb-2">Nie posiadasz jeszcze konta?
                    <a href="{% url 'register' %}">Zarejestruj tutaj</a>
                  </div>
                  <div class="text-center mb-2">Posiadasz konto?
                    <a href="{% url 'login' %}">Przejdż do logowania</a>
                  </div>
    
            </form>




{% endblock %}

projekt/app/templates/register.html
{% extends 'base.html' %}
{% block title %}
Rejestracja
{% endblock %}
{% block content %}
           
<h4 class="text-left">Rejestracja użytkownika</h4>
<hr class="my-4">
<form method="POST" action="{% url 'register' %}">
    {% csrf_token %}

    <div class="form-group2">
        

    {{ form.as_p }}

</div >

    <input type="submit" value="Zarejestruj" class="btn btn-dark">
    <hr class="my-4">
    <div class="text-left mb-2"> Zakładając konto akceptujesz 
        <a href="{% url 'reg' %}">regulamin</a> oraz <a href="{% url 'pp' %}">politykę prywatności.</a>
      </div>
</form>
    {% endblock %}

projekt/app/templates/start.html
{% extends 'base.html' %}
{% block title %}
Strona startowa

{% endblock %}
{% block content %}
           


<form method="POST" action="{% url 'start' %}">
<div class="text-left">
    <h4 class="title">Witaj! </h4>
    <hr class="my-4">
<p>
   <p> PredApp to aplikacja, która umożliwia przewidywanie<br>
     ceny samochodów oraz wynajmu mieszkań w Warszawie.</p>
    <p>Korzystając z szeregu różnorodnych danych, aplikacja generuje<br>
      prognozy cenowe dla konkretnych ofert.</p>
       Dzięki temu użytkownicy mogą lepiej planować swoje wydatki i <br>
    uniknąć przepłacania podczas zakupu samochodu lub
     wynajmu mieszkania. </p>
</p>
</div>
<hr class="my-4">
<div class="mb-2 text-center">
    <button type="submit" class="btn  btn-block text-uppercase">
        <a id="log" class="btn btn-dark" href="{% url 'login' %}">Przejdź do logowania</a>
    </button>
      </div><div class="mb-2 text-center">
        <button type="submit" class="btn  btn-block text-uppercase">
            <a id="reg" class="btn btn-dark" href="{% url 'register' %}">Przejdź do rejestracji</a>
        </button>
          </div>
          <hr class="my-4">

</form>
    {% endblock %}