projekt/app/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('start', views.start, name="start"),
    path('home', views.home, name="home"),
    path('login/', views.login_user, name="login"), 
    path('logout/', views.logout_user, name="logout"),
    path('register/', views.create_user, name="register"),
    path('profil/', views.profil, name="profil"),
    path('edit/', views.edit, name="edit"),
    path('change_password/', views.change_password, name="change_password"),
    path('social-auth/', include('social_django.urls', namespace='social')),

      path('password_reset/',auth_views.PasswordResetView.as_view(template_name="account/password_reset.html"),name='password_reset'),
      path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_done.html"),name='password_reset_done'),
      path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_confirm.html"),name='password_reset_confirm'),
      path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name="account/password_reset_complete.html" ),name='password_reset_complete'),

      path('reg/', views.reg, name="reg"),
      path('pp/', views.pp, name="pp"),
      path('email/', views.contact, name="email"),
      path('contact/', views.contact, name="contact"),
]

projekt/predcar/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers
router = routers.DefaultRouter()
router.register('pred_car',views.Pred_carViews)
app_name='predcar'
urlpatterns = [
     
     path('api/', include(router.urls)),
   
    
     
     path('predcar/add/', views.create_view, name='add'),
     path('predictor_car', views.predictor_car, name='predictor_car'),
     
 
     path('pred/ajax/load-models/', views.load_models, name='ajax_load_models'),
    
]

projekt/projekt/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('predhouse.urls')),
    path('', include('predcar.urls')),
    path('captcha/', include('captcha.urls'))
]

projekt/predcar/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Mark(models.Model):
    name = models.TextField(max_length=10,blank=False,verbose_name="Marka")
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Marka"
        verbose_name_plural = "Marki"
    
 
class Model(models.Model):

    
    mark = models.ForeignKey(Mark, on_delete=models.CASCADE, verbose_name="Marka",blank=False,)
    name = models.TextField(max_length=10,verbose_name="Model",blank=False,)
 
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Model"
        verbose_name_plural = "Modele"


class Pred_car(models.Model):
    CHOICES_FUEL = [
    (0, 'Diesel'),(1, 'Elektryczny'),(2, 'Benzyna'),(3, 'Hybryda'),(4, 'LPG'),]
    
    CHOICES_PROVINCE = [
    (0, 'Dolnośląskie'),(1, 'Kujawsko-pomorskie'),(2, 'Lubelskie'),(3, 'Lubuskie'),(4, 'Mazowieckie'), (5, 'Małopolskie'),(6, 'Opolskie'),(7, 'Podkarpackie'),(8, 'Podlaskie'),
     (9, 'Pomorskie'),(10, 'Warmińsko-mazurskie'),(11, 'Wielkopolskie'),(12, 'Zachodniopomorskie'), (13, 'Łódzkie'),(14, 'Śląskie'),(15, 'Świętokrzyskie')
    ]
    CHOICES_YEAR = [
    (1992, '1992'),(1993, '1993'),(1994, '1994'),(1995, '1995'),(1996, '1996'),
    (1997, '1997'),(1998, '1998'),(1999, '1999'),(2000, '2000'),(2001, '2001'),(2002, '2002'),(2003, '2003'),(2004, '2004'),(2005, '2005'),(2006, '2006'),(2007, '2007'),(2008, '2008'),
    (2009, '2009'),(2010, '2010'),(2011, '2011'),(2012, '2012'),(2013, '2013'),(2014, '2014'),(2015, '2015'),(2016, '2016'),(2017, '2017'),(2018, '2018'),(2019, '2019'),(2020, '2020'),
    (2021, '2021'),(2022, '2022')]

    
    mark=models.ForeignKey(Mark, on_delete=models.SET_NULL, blank=False, null=True,verbose_name="Marka")
    model=models.ForeignKey(Model, on_delete=models.SET_NULL,blank=False, null=True,verbose_name="Model")
    
    year=models.PositiveIntegerField(choices=CHOICES_YEAR,verbose_name="Rok produkcji",blank=False)
    mileage=models.PositiveIntegerField( verbose_name="Przebieg km:   max przebieg do 2000000km",validators=[ MaxValueValidator(2000000), MinValueValidator(1)],blank=False)
    vol_engine=models.PositiveIntegerField(max_length=6, verbose_name="Pojemniść silnika : między 500cm3 a 5000cm3",validators=[ MaxValueValidator(5000), MinValueValidator(0)],blank=False)
    
    fuel=models.PositiveIntegerField(max_length=10,choices=CHOICES_FUEL,blank=False, verbose_name="Rodzaj paliwa")
    province=models.PositiveIntegerField(max_length=10,choices=CHOICES_PROVINCE,blank=False, verbose_name="Województwo")

    class Meta:
        verbose_name = "Predykcja"
        verbose_name_plural = "Predykcje"
    

projekt/predcar/forms.py
from django import forms
from .models import Pred_car, Model 

class Pred_car_Form(forms.ModelForm):
    class Meta:
        model=Pred_car
        fields= '__all__'
        widgets = {
            'mark': forms.Select(attrs={ 'class': 'form-select' }),
            'model': forms.Select(attrs={ 'class': 'form-select' }),

            'year': forms.Select(attrs={ 'class': 'form-control' }),
            'mileage': forms.TextInput(attrs={ 'class': 'form-control' }),
            'vol_engine': forms.TextInput(attrs={ 'class': 'form-control','placeholder': 'Jeśli wybrałeś silnik elektryczny wpisz 1' }),

            'fuel': forms.Select(attrs={ 'class': 'form-select' }),
            'province': forms.Select(attrs={ 'class': 'form-select' }),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['model'].queryset=Model.objects.none()

        if 'mark' in self.data:
            try:
                mark_id=int(self.data.get('mark'))
                self.fields['model'].queryset=Model.objects.filter(mark_id=mark_id).order_by('name')
            except(ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['model'].queryset= self.instance.mark.model_set.order_by('name')

projekt/predcar/views.py
from django.shortcuts import render
from rest_framework import viewsets
from rest_framework.decorators import api_view
from django.core import serializers
from rest_framework.response import Response
from rest_framework import status
from django.http import JsonResponse
from rest_framework.parsers import JSONParser
from . models import Mark,Model,Pred_car
from . serializers import pred_carSerializers
import pickle
import joblib
import requests
import json
import numpy as np
import pandas as pd
from django.shortcuts import render, redirect, get_object_or_404
from .forms import Pred_car_Form
from rest_framework import views
from rest_framework.views import APIView
from django.contrib.auth.decorators import login_required
import xgboost as xgb
from django.contrib.auth.models import User
from rest_framework.permissions import IsAuthenticated


#loaded_model = joblib.load(open('C:\\Users\\patry\\OneDrive\\Pulpit\\inzzza\\carr', 'rb'))

class Pred_carViews(viewsets.ModelViewSet,):   
    queryset=Pred_car.objects.all()
    serializer_class=pred_carSerializers

    def get_object(self):
        return Pred_car.objects.latest('id')
    def latest(self, request):
        latest_model = self.get_queryset().latest('id')
        serializer = self.get_serializer(latest_model)
        return Response(serializer.data)





@login_required
def create_view(request):
    user = request.user
    form = Pred_car_Form()
    if request.method == 'POST':
        form = Pred_car_Form(request.POST)
        if form.is_valid():
            form.save()
            return redirect('predcar:predictor_car')
    return render(request, 'pred_car.html', {'form': form})

def load_models(request):
    mark_id = request.GET.get('mark_id')
    modelss = Model.objects.filter(mark_id=mark_id).all()
    return render(request, 'drop_list.html', {'modelss': modelss})



@api_view(['GET'])
def index(request):
    return_data = {
        "error_code" : "0",
        "info" : "success",
    }
    return Response(return_data)

@login_required
def predictor_car(request):
    user = request.user
    url = 'http://127.0.0.1:8000/api/pred_car/latest'
    response = requests.get(url)
    if response.status_code == 200:
        jk = response.json()
        k = np.array(list(jk.values()))

        to_predict = {}
        for key, value in jk.items():
            to_predict[key] = [value]
        loaded_model = xgb.Booster()
        loaded_model.load_model("C:\\Users\\patry\\OneDrive\\Pulpit\\inzzza\\App\\projekt\\model_pred_car.json")  
        pred = xgb.DMatrix(pd.DataFrame(to_predict)) 
        status=loaded_model.predict(pred)
       
        formatted_data = []

        for i, (key, value) in enumerate(jk.items(), 1):
            formatted_data.append(value)
        v1, v2, v3, v4, v5, v6, v7 = formatted_data
        stat=int(status[0])
        mark=Mark.objects.filter(pk=v1).last
        model=Model.objects.filter(pk=v2).last
        car = Pred_car.objects.filter().last
    else:
        print('Nie udało się pobrać modelu')
    context={'stat': stat,'car': car,'mark':mark,'model':model}
    return render(request, 'predictor_car.html', context)

projekt/predcar/templates/drop_list.html
<option value="">---------</option>
{% for model in modelss %}
<option value="{{ model.pk }}">{{ model.name }}</option>
{% endfor %}

projekt/predcar/templates/pred_car.html
{% extends 'baseapp.html' %}

{% block content %}
<div class="form-reset3">
<form method="post" id="MemberForm" data-models-url="{% url 'predcar:ajax_load_models' %}"  class="form-horizontal" role="form"   >
    <hr class="my-4">
    {% csrf_token %}
<h4 class="text-center"> Wypełnij formularz, a dowiesz się ile kosztuje poszukiwane przez Ciebie Auto</h4>    
<div class="row">
    <div class="col">
        <label>Marka</label>
        {{ form.mark}}
      </div>
          <div class="col">
            <label>Model </label>
            {{ form.model }}
          </div>
          
          
        </div>

        <div class="row">
            <div class="col">
              <label>Rok produkcji</label>
              {{ form.year }}
            </div>
            <div class="col">
              <label>Przebieg <small>(max. 2 mln km)</small></label>
              {{ form.mileage}}
            </div>
    
          </div>

           <div class="row">
            <div class="col">
              <label>Silnik</label>
              {{ form.fuel }}
            </div>
            <div class="col">
              <label>Pojemność <small>(500 cm3 - 5000 cm3)</small></label>
              {{ form.vol_engine}}
            </div>
            
          </div>

           
          <div class="row">
            <div class="col">
              <label>Województwo</label>
              {{ form.province }}
            </div>
            <div class="col">
            </div>
            
          </div> <hr class="my-4">
          <input  type="submit" value="Predykcja" class="btn btn-dark">


          <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
          <script>
              $("#id_mark").change(function () {
              const url = $("#MemberForm").attr("data-models-url");  
                 const markId = $(this).val();  
       
               $.ajax({                       
                   url: url,                    
                  data: {
                      'mark_id': markId       
                  },
                  success: function (data) {   
                      $("#id_model").html(data); 
                   }
              });
       
              });
                  </script>
      </form>
    </div>
     
{% endblock %}

projekt/predcar/templates/predictor_car.html
{% extends 'baseapp.html' %}

{% block content %}
<hr class="my-4">
<h4>
<div class="row ac">
<div class="col">
    Marka:<strong> {{ mark }}</strong>
  </div>
  <div class="col">
    Model:<strong>  {{ model }}</strong>
  </div>
  <div class="col">
    Rok produkcji: <strong> {{ car.year }}</strong>
  </div>
</div>
<div class="row ac">
<div class="col">
    Przebieg: <strong> {{ car.mileage }} km</strong> 
  </div>
  <div class="col">
    Slinik:<strong> 
{% if car.fuel == 0 %}
    Diesel
{% elif  car.fuel  == 1 %}
Elektryczny
{% elif  car.fuel  == 2 %}
    Benzyna
{% elif  car.fuel  == 3 %}
Hybryda
{% elif  car.fuel  == 4 %}
LPG
{% endif %}</strong>
  </div>
  <div class="col">
    Pojemność:<strong>  {{ car.vol_engine }} cm3</strong> 
  </div>
</div>
<div class="row ac">
<div class="col">
    Województwo :<strong> 
{% if car.province == 0 %}
    Dolnośląskie
{% elif  car.province  == 1 %}
    Kujawsko-pomorskie
{% elif  car.province  == 2 %}
    Lubelskie
{% elif  car.province  == 3 %}
Lubuskie
{% elif  car.province  == 4 %}
Mazowieckie
{% elif car.province == 5 %}
    Małopolskie
{% elif  car.province  == 6 %}
    Opolskie
{% elif  car.province  == 7 %}
    Podkarpackie
{% elif  car.province  == 8 %}
Podlaskie
{% elif  car.province  == 9 %}
Pomorskie
{% elif car.province == 10 %}
    Warmińsko-mazurskie
{% elif  car.province  == 11 %}
    Wielkopolskie
{% elif  car.province  == 12 %}
    Zachodniopomorskie
{% elif  car.province  == 13 %}
Łódzkie
{% elif  car.province  == 14 %}
Śląskie
{% elif  car.province  == 15 %}
Świętokrzyskie
{% endif %}<strong> 
  
  <div class="col">
    
  </div>
</div>
</h4>


</div>



<hr class="my-4">
<p></p><h3 class="text-center">Przewidywana cena poszukiwanego samochodu wynosi: <h2 class="text-center"><strong>{{ stat }} zł</strong></h2> </h3>



{% endblock %}